services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    # volumes:
    #   - ./mongo-data:/data/db
    env_file:
      - global.env
      - mongodb.env

  data-seeder:
    image: saichovsky/mongo-data-seeder:latest
    build: .
    depends_on:
      - mongodb
    env_file:
      - global.env
      - data-seeder.env

    command: ["python", "seed_script.py", "--db-name", "testdb"]

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    env_file:
      - global.env
      - data-seeder.env
    depends_on:
      - mongodb
      - data-seeder
